# Generated by Django 5.0.3 on 2024-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=20)),
                ('account_type_id', models.CharField(max_length=1)),
                ('amount', models.FloatField()),
                ('cheque_id', models.CharField(max_length=10)),
                ('cost_center_id', models.CharField(max_length=10)),
                ('dont_return_serial', models.BooleanField()),
                ('exchange_rate', models.FloatField()),
                ('forward_remark', models.TextField(blank=True, null=True)),
                ('instrument_type_id', models.CharField(max_length=1)),
                ('local_amount', models.FloatField()),
                ('main_gl_id', models.CharField(max_length=10)),
                ('mean_rate', models.FloatField()),
                ('module_id', models.CharField(max_length=10)),
                ('operator_id', models.CharField(max_length=10)),
                ('other_details', models.JSONField(blank=True, default=list)),
                ('our_branch_id', models.CharField(max_length=10)),
                ('portfolio_account_id', models.CharField(blank=True, max_length=10, null=True)),
                ('portfolio_branch_id', models.CharField(blank=True, max_length=10, null=True)),
                ('portfolio_series', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('profit', models.FloatField()),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(max_length=255)),
                ('serial_id', models.CharField(max_length=10)),
                ('sl_no', models.CharField(max_length=10)),
                ('trx_amount', models.FloatField()),
                ('trx_branch_id', models.CharField(max_length=10)),
                ('trx_code_id', models.CharField(max_length=10)),
                ('trx_currency_id', models.CharField(max_length=10)),
                ('trx_date', models.DateField()),
                ('trx_description', models.CharField(max_length=255)),
                ('trx_description_id', models.CharField(max_length=10)),
                ('trx_flag_id', models.CharField(blank=True, max_length=10, null=True)),
                ('trx_type_id', models.CharField(max_length=10)),
                ('value_date', models.DateField()),
            ],
        ),
    ]
