# Generated by Django 5.0.3 on 2024-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trx_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.CharField(max_length=15),
        ),
    ]
