# Generated by Django 5.0.3 on 2024-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilee', '0002_alter_transaction_trx_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trx_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.DateTimeField(),
        ),
    ]
