# Generated by Django 5.0.3 on 2024-06-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilee', '0003_alter_transaction_trx_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cheque_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cheque_date',
            field=models.DateTimeField(null=True),
        ),
    ]
