# Generated by Django 5.0.3 on 2024-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilee', '0004_remove_transaction_cheque_id_transaction_cheque_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cheque_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cheque_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
