# Generated by Django 5.0.3 on 2024-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubilee', '0005_remove_transaction_cheque_date_transaction_cheque_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='other_details',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
