# Generated by Django 4.2.4 on 2023-12-20 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_bou_code', models.CharField(default='UG001', max_length=7)),
                ('partner_branch_code', models.CharField(default='001', max_length=3)),
                ('application_date', models.DateField()),
                ('partner_reference', models.CharField(max_length=15)),
                ('identity_id_number', models.CharField(max_length=15)),
                ('identity_type_code', models.CharField(choices=[('IDT04', 'Financial Card Number'), ('IDT10', 'Country National ID Number')], default='IDT04', max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('currency_code', models.CharField(default='UGX', max_length=15)),
                ('application_amount', models.CharField(max_length=15)),
                ('application_duration', models.CharField(max_length=15)),
                ('product_type_code', models.CharField(max_length=15)),
                ('application_type_code', models.CharField(max_length=15)),
                ('generate_report', models.CharField(default='true', max_length=5)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
