# Generated by Django 4.2.4 on 2023-12-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0002_remove_cap_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cap',
            name='created_on',
        ),
    ]
