# Generated by Django 4.2.4 on 2023-12-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0003_remove_cap_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='amount_approved',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cap',
            name='application_rejection_reason',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cap',
            name='application_rejection_reason_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cap',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='cap',
            name='application_status_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cap',
            name='application_status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cap',
            name='approved_duration',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cap',
            name='identity_id_number',
            field=models.CharField(max_length=20),
        ),
    ]
