# Generated by Django 4.2.4 on 2023-12-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(max_length=15)),
                ('identity_type', models.CharField(choices=[('4', 'Financial Card Number'), ('10', 'Country National ID Number')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(max_length=15)),
                ('fcs', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=150)),
                ('forename1', models.CharField(max_length=150)),
                ('forename2', models.CharField(max_length=150)),
                ('forename3', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
            ],
        ),
    ]
