# Generated by Django 4.2.4 on 2023-12-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0006_identity_identitydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydetail',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
    ]
