# Generated by Django 4.2.4 on 2023-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0007_alter_identitydetail_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydetail',
            name='forename1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='forename2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='forename3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
