# Generated by Django 4.2.4 on 2023-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0008_alter_identitydetail_forename1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cap',
            name='partner_bou_code',
        ),
        migrations.AlterField(
            model_name='cap',
            name='application_status',
            field=models.CharField(choices=[('0', 'Approved'), ('1', 'Cancelled by Borrower'), ('2', 'Pending'), ('6', 'Rejected by PI'), ('5', 'Rejected by Borrower')], default='2', max_length=15),
        ),
        migrations.AlterField(
            model_name='cap',
            name='product_type_code',
            field=models.CharField(choices=[('0', 'Guarantee'), ('1', 'Hire Purchase'), ('2', 'Leasing'), ('3', 'Letter of Credit'), ('4', 'Line of Credit'), ('6', 'Mortgage'), ('7', 'Overdraft'), ('8', 'Bond'), ('9', 'Revolving Credit Facility'), ('10', 'Unsecured Loan'), ('11', 'Secured Loan'), ('12', 'Higher Education Student’s Loan1'), ('13', 'Invoice Discounting'), ('14', 'Mobile Loan'), ('15', 'Small Business Recovery Fund (SBRF)2'), ('16', 'Agricultural Credit Facility (ACF)3')], max_length=50),
        ),
    ]
