# Generated by Django 4.2.4 on 2023-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0009_remove_cap_partner_bou_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='partner_bou_code',
            field=models.CharField(default='UG001', max_length=7),
        ),
    ]
