# Generated by Django 4.2.4 on 2024-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0010_cap_partner_bou_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='application_type_code',
            field=models.CharField(choices=[('I', 'Individual'), ('B', 'Business')], max_length=15),
        ),
    ]
