# Generated by Django 4.2.4 on 2024-01-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0011_alter_cap_application_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydetail',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
