# Generated by Django 4.2.4 on 2024-01-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0012_identitydetail_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydetail',
            name='user_image',
        ),
    ]
