# Generated by Django 4.2.4 on 2024-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0013_remove_identitydetail_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydetail',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='ds/'),
        ),
    ]
