# Generated by Django 4.2.4 on 2024-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0014_identitydetail_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydetail',
            name='user_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
