# Generated by Django 4.2.4 on 2024-01-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0016_alter_identitydetail_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitydetail',
            old_name='user_image',
            new_name='image',
        ),
    ]
