# Generated by Django 4.2.4 on 2024-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0018_alter_identitydetail_fcs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OurBranchID', models.CharField(max_length=5)),
                ('ApplicationID', models.CharField(max_length=100)),
                ('ModuleID', models.CharField(max_length=100)),
                ('ApiOperatorID', models.CharField(default='MN1519', max_length=200)),
            ],
        ),
    ]
