# Generated by Django 4.2.4 on 2024-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0018_boucode_branchcode_alter_cap_partner_bou_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydetail',
            name='fcs',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='identity_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
