# Generated by Django 4.2.4 on 2024-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0019_coreapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='partner_bou_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cap',
            name='partner_branch_code',
            field=models.CharField(max_length=20),
        ),
    ]
