# Generated by Django 4.2.4 on 2024-01-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0020_alter_cap_partner_bou_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreapplication',
            name='ModuleID',
        ),
    ]
