# Generated by Django 4.2.4 on 2024-01-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0021_remove_coreapplication_moduleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreapplication',
            name='ApiOperatorID',
        ),
    ]
