# Generated by Django 4.2.4 on 2024-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0022_remove_coreapplication_apioperatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='application_date',
            field=models.DateTimeField(),
        ),
    ]
