# Generated by Django 4.2.4 on 2024-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0023_alter_cap_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='report_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
