# Generated by Django 4.2.4 on 2024-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0024_cap_report_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='application_amount',
            field=models.FloatField(max_length=15),
        ),
    ]
