# Generated by Django 4.2.4 on 2024-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0025_alter_cap_application_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('4', 'Financial Card Number'), ('10', 'Country National ID Number')], max_length=15)),
                ('report_pull_reason', models.CharField(choices=[('1', 'New Credit Application'), ('2', 'Review Of Existing Credit'), ('3', 'Customer Report Request'), ('4', 'Review Existing Credit'), ('5', 'Stakeholder/Guarantor Report')], max_length=15)),
                ('report_type', models.CharField(choices=[('4', 'Compact Report'), ('2', 'Standard Report'), ('3', 'Enhanced Report'), ('4', 'Score Report')], max_length=15)),
            ],
        ),
    ]
