# Generated by Django 5.0.3 on 2024-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metropol', '0027_alter_cap_identity_type_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cap',
            old_name='partner_reference',
            new_name='application_reference',
        ),
        migrations.AlterField(
            model_name='report',
            name='identity_type',
            field=models.CharField(choices=[('IDT01', 'Registration Number'), ('IDT02', 'Tax Identification Number'), ('IDT04', 'Financial Card Number'), ('IDT05', 'Passport Number'), ('IDT10', 'National Identity Number'), ('IDT16', 'Refugee Number'), ('IDT17', 'Work Permit Number')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_pull_reason',
            field=models.CharField(choices=[('RP01', 'New Credit Application'), ('RP02', 'Review Of Existing Credit'), ('RP03', 'Customer Report Request'), ('RP05', 'Stakeholder/Guarantor Report')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('CR01', 'Compact Report'), ('CR02', 'Standard Report'), ('CR03', 'Enhanced Report'), ('CR04', 'Score Report'), ('CR06', 'Identification Report')], max_length=15),
        ),
    ]
