# Generated by Django 4.2.4 on 2023-12-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('account_number', models.BigIntegerField(default=0)),
                ('accountBalance', models.BigIntegerField(default=0)),
                ('mobile_number', models.CharField(default=0, max_length=9)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crm.branch')),
            ],
        ),
    ]
