# Generated by Django 4.2.4 on 2023-08-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('middlename', models.CharField(blank=True, max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField(db_comment='Birth Date')),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('tel', models.CharField(max_length=60)),
                ('national_id', models.CharField(max_length=12)),
                ('occupation', models.CharField(blank=True, max_length=25)),
                ('date_joined', models.DateField(db_comment='Birth Date')),
                ('status', models.CharField(choices=[('live', 'Live'), ('deceased', 'Deceased')], max_length=10)),
                ('kin_name', models.CharField(max_length=60)),
                ('kin_relationship', models.CharField(max_length=60)),
                ('kin_tel', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_tin', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.branch')),
            ],
        ),
        migrations.CreateModel(
            name='LandTitleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('security_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('borrower', 'Borrower'), ('Powers_of_the_Attorney', 'Powers of the Attorney')], max_length=50)),
                ('Security_owner', models.CharField(max_length=20)),
                ('Lease_Hold_Tenure', models.CharField(max_length=50)),
                ('LeaseHoldExpiryDate', models.DateField()),
                ('DateRecieved', models.DateField()),
                ('ForcedSaleValue', models.CharField(max_length=100)),
                ('Security_Description', models.CharField(max_length=100)),
                ('Insurance_Details', models.CharField(max_length=100)),
                ('LandTitleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.landtitletype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.customer')),
                ('security_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitystatus')),
                ('security_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype')),
            ],
        ),
        migrations.AddField(
            model_name='landtitletype',
            name='security_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype'),
        ),
    ]
