# Generated by Django 4.2.4 on 2023-09-17 08:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('middlename', models.CharField(blank=True, max_length=60, null=True)),
                ('lastname', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=5)),
                ('national_id', models.CharField(blank=True, max_length=12, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('bank_tin', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LandTitleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('security_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('borrower', 'Borrower'), ('Third_Party', 'Third Party')], max_length=50)),
                ('status', models.CharField(choices=[('InCustody', 'In Custody'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired'), ('Recieved', 'Recieved')], default='InCustody', max_length=50)),
                ('security_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('Security_owner', models.CharField(max_length=20)),
                ('LeaseHoldStartDate', models.DateField(blank=True, null=True)),
                ('Lease_Hold_Tenure', models.IntegerField(blank=True, null=True)),
                ('Security_Description', models.CharField(max_length=100)),
                ('withdrawn_on', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sent_for_mortgaging_at', models.DateField(default=datetime.datetime.now)),
                ('sent_for_further_charge_at', models.DateField(default=datetime.datetime.now)),
                ('LandTitleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.landtitletype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.customer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('security_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitystatus')),
                ('security_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype')),
                ('sent_for_further_charge_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_for_further_charge_by', to=settings.AUTH_USER_MODEL)),
                ('sent_for_mortgaging_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_for_mortgaging_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='landtitletype',
            name='security_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.securitytype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_Name', models.CharField(max_length=20)),
                ('Contract_value', models.FloatField(max_length=20)),
                ('DateSigned', models.DateField(default=datetime.datetime.now)),
                ('Duration', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('on', 'On'), ('Expired', 'Expired'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='on', max_length=50)),
                ('Expiry_Date', models.DateField(default=datetime.datetime.now)),
                ('Description', models.CharField(max_length=200)),
                ('Compulsory_Terms', models.CharField(max_length=200)),
                ('InsuranceTerms', models.CharField(max_length=200)),
                ('contract_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
