# Generated by Django 4.2.4 on 2023-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='file_sec',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='security',
            name='status',
            field=models.CharField(choices=[('InCustody', 'In Custody'), ('Withdrawn', 'Withdrawn'), ('Expired', 'Expired'), ('Recieved', 'Recieved')], default='InCustody', max_length=50),
        ),
    ]
