# Generated by Django 4.2.4 on 2023-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0002_security_file_sec_security_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='withdrawn_on',
            field=models.DateField(null=True),
        ),
    ]
