# Generated by Django 4.2.4 on 2023-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0003_security_withdrawn_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='withdrawn_on',
            field=models.DateField(),
        ),
    ]
