# Generated by Django 4.2.4 on 2023-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0003_customuser_firstname_customuser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
