# Generated by Django 4.2.4 on 2023-09-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0004_customuser_password1_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
