# Generated by Django 4.2.4 on 2023-08-29 09:24

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0006_security_created_at_security_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='withdrawn_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
