# Generated by Django 4.2.4 on 2024-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0007_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
