# Generated by Django 4.2.4 on 2023-08-29 11:59

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0007_alter_security_withdrawn_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='created_at',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
