# Generated by Django 4.2.4 on 2024-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0008_alter_customer_gender_alter_customer_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='needs_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
