# Generated by Django 4.2.4 on 2023-08-29 12:00

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0008_alter_security_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='withdrawn_on',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
