# Generated by Django 4.2.4 on 2023-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0010_alter_security_withdrawn_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='Insurance_Details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='security',
            name='Lease_Hold_Tenure',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
