# Generated by Django 4.2.4 on 2023-08-30 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0011_alter_security_insurance_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='security',
            name='withdrawn_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
