# Generated by Django 4.2.4 on 2023-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0012_alter_security_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitystatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
