# Generated by Django 4.2.4 on 2023-09-01 06:17

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LegalDoc', '0013_alter_securitystatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='sent_for_mortgaging_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_for_mortgaging_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
