# Generated by Django 4.2.4 on 2023-09-01 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0014_security_sent_for_mortgaging_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='sent_for_mortgaging_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
