# Generated by Django 4.2.4 on 2023-09-01 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0015_security_sent_for_mortgaging_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
