# Generated by Django 4.2.4 on 2023-09-01 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LegalDoc', '0016_alter_security_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='sent_for_further_charge_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='security',
            name='sent_for_further_charge_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_for_further_charge_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
