# Generated by Django 4.2.4 on 2023-09-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0017_security_sent_for_further_charge_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank_branch',
        ),
        migrations.AddField(
            model_name='security',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LegalDoc.branch'),
            preserve_default=False,
        ),
    ]
