# Generated by Django 4.2.4 on 2023-09-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegalDoc', '0022_customer_created_by_alter_customer_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-id',)},
        ),
    ]
