# Generated by Django 5.0.3 on 2024-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=50)),
                ('accountholderstatus', models.CharField(max_length=50)),
                ('profilename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepositFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankcode', models.CharField(default=37, max_length=30)),
                ('accountnumber', models.CharField(blank=True, default='20680300000', max_length=15, null=True)),
                ('amount', models.FloatField(max_length=15)),
                ('receiver', models.CharField(max_length=20)),
                ('transactiontimestamp', models.DateTimeField(default='2024-06-12T13:37:26')),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('banktransactionid', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=50)),
                ('receiverfirstname', models.CharField(max_length=50)),
                ('receiversurname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
