# Generated by Django 5.0.3 on 2024-06-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstructionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentinstructionid', models.CharField(max_length=20)),
                ('receiverbankcode', models.CharField(max_length=10)),
                ('receiveraccountnumber', models.CharField(max_length=20)),
                ('receiverfirstname', models.CharField(max_length=50)),
                ('receiversurname', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecw.amount')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentInstruction',
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-13T12:44:59'),
        ),
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='transactiontimestamp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecw.transactiontimestamp'),
        ),
    ]
