# Generated by Django 5.0.3 on 2024-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0006_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-14T12:46:26'),
        ),
    ]
