# Generated by Django 5.0.3 on 2024-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0009_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='transactionid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='transmissioncounter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-18T14:25:52'),
        ),
    ]
