# Generated by Django 5.0.3 on 2024-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0010_paymentinstructionrequest_transactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-18T14:56:18'),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='receiverbankcode',
            field=models.CharField(max_length=20),
        ),
    ]
