# Generated by Django 5.0.3 on 2024-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0011_alter_depositfunds_transactiontimestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfunds',
            name='trx_batchid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositfunds',
            name='trx_serialid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-18T15:44:51'),
        ),
    ]
