# Generated by Django 5.0.3 on 2024-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0012_depositfunds_trx_batchid_depositfunds_trx_serialid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='receiver',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-18T17:33:48'),
        ),
    ]
